# Generated by Django 5.1.4 on 2024-12-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('commercialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secteur.commercialization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secteur.produit')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secteur.representative')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secteur.secteur')),
            ],
        ),
    ]
